# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get_content_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: esciencecenter-digital-skills/NEBULA
          ref: main
          sparse-checkout: config.json
          sparse-checkout-cone-mode: false
          path: ./content_config/
    
      - name: Show config path
        run: |
          pwd
          ls -la
          cd content_config
          ls -la
          cd -

      - name: Upload content config file
        uses: actions/upload-artifact@v4
        with:
          name: content_config
          path: ./content_config/config.json

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run CI on Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build