name: Clean install and build check (no deploy) with specified content

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_with_NEBULA:
    permissions: 
      contents: write
    uses: ./.github/workflows/deploy.yml
    with:
      content_organization: esciencecenter-digital-skills
      content_repository: research-software-support
      content_ref: NEBULA-update
      base_url: NEBULA
      nebula_ref: ${{ github.sha }}
      deploy_to_ghpages: false
