name: Deploy to gh-pages

on:
  workflow_call:
    inputs:
      content-repo: 
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: esciencecenter-digital-skills/NEBULA
          path: /NEBULA

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Checkout
        uses: actions/checkout@v3
        path: /NEBULA/content

      - name: Check contents
        run: |
          pwd
          ls -la

      - name: Generate
        run: npx nuxi generate

      - name: Check generated contents
        run: |
          pwd
          ls -la
          cd .output/public
          pwd
          ls -la

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
