name: Deploy to gh-pages

on: 
  push:
    branches:
    workflow_dispatch:

jobs:
  get_content_config:
    steps:
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          # the line below should be removed to specify the calling repo
          repository: esciencecenter-digital-skills/research-software-support 
          sparse-checkout: config.json
          sparse-checkout-cone-mode: false
          path: ./content_config
    
      - name: Show config path
        run: |
          pwd
          ls -la
          cd content_config
          ls -la
          cd -

      - name: Upload content config file
        uses: actions/upload-artifact@v4
        with:
          name: content_config
          path: config.json

  deploy_with_NEBULA:
    needs: get_content_config
    permissions: 
      contents: write
    uses: esciencecenter-digital-skills/NEBULA/.github/workflows/deploy.yml@configuration
      with:
        config_artifact_name: content_config
