name: Deploy to gh-pages

on:
  workflow_call:
    inputs:
      content_organization: 
        required: true
        type: string
      content_repository: 
        required: true
        type: string
      content_ref: 
        required: true
        type: string
      nebula_ref:
        required: true
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.content_organization }}/${{ inputs.content_repository }}
          ref: ${{ inputs.content_ref }}
          path: ./${{ inputs.content_repository }}
      
      - name: Check content
        run: |
          pwd
          ls -la
          cd ./${{ inputs.content_repository }}
          ls -la

      - name: Set environment variable
        run: |
          echo "CONFIG_PATH=${PWD}/${{ inputs.content_repository }}/config.json" >> $GITHUB_ENV

      - name: test environment variable
        run: |
          echo $CONFIG_PATH 
          cd $CONFIG_PATH
          pwd
          ls -la
          cat config.json

      - name: Checkout NEBULA framework
        uses: actions/checkout@v4
        with:
          repository: esciencecenter-digital-skills/NEBULA
          ref: ${{ inputs.nebula_ref }}
          path: ./NEBULA

      - name: Check current NEBULA 
        run: | 
          echo "Workflow NEBULA ref=$GITHUB_REF"
          echo "Checked-out NEBULA ref=${{ inputs.nebula_ref }}"
          cd ./NEBULA
          pwd
          ls -la

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies
        run: |
          pwd
          ls -la
          cd NEBULA
          pwd
          ls -la
          npm ls | grep nuxt
          npm ci
          npm ls | grep nuxt

      - name: Generate
        run: |
          cd NEBULA
          npx nuxi generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./NEBULA/.output/public
