name: Deploy to gh-pages

on:
  push:
    branches:
      - main
      - design-update
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Generate
        run: npx nuxi generate
      - name: Check generated contents
        run: |
          pwd
          ls -la
          cd .output/public
          pwd
          ls -la
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
