name: Deploy to gh-pages

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_with_NEBULA:
    permissions: 
      contents: write
    uses: esciencecenter-digital-skills/NEBULA/.github/workflows/deploy.yml${{ github.sha }}
    with:
      content_organization: esciencecenter-digital-skills
      content_repository: research-software-support
      content_ref: main
      nebula_ref: ${{ github.sha }}

